// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDeEstacionamentos;

namespace SistemaGestaoEstacionamentos.Migrations
{
    [DbContext(typeof(SistemaEstacionamentosContext))]
    [Migration("20190801135704_teste3")]
    partial class teste3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaDeEstacionamentos.Estacionamento", b =>
                {
                    b.Property<int>("Handle")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Handle");

                    b.ToTable("Estacionamentos");
                });

            modelBuilder.Entity("SistemaDeEstacionamentos.Model.Tickets", b =>
                {
                    b.Property<int>("Handle")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Handle");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("SistemaDeEstacionamentos.Model.Veiculos", b =>
                {
                    b.Property<int>("Handle")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Placa");

                    b.Property<string>("TipoDoCarro");

                    b.HasKey("Handle");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("SistemaDeEstacionamentos.Usuarios", b =>
                {
                    b.Property<int>("Handle")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf");

                    b.Property<string>("Nome");

                    b.Property<int>("cep");

                    b.Property<string>("nomeDeUsuario");

                    b.Property<string>("senha");

                    b.HasKey("Handle");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaDeEstacionamentos.Vagas", b =>
                {
                    b.Property<int>("Handle")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EstacionamentoHandle");

                    b.Property<string>("LocalDaVaga");

                    b.Property<string>("TipoDaVaga");

                    b.HasKey("Handle");

                    b.HasIndex("EstacionamentoHandle");

                    b.ToTable("Vagas");
                });

            modelBuilder.Entity("SistemaDeEstacionamentos.Vagas", b =>
                {
                    b.HasOne("SistemaDeEstacionamentos.Estacionamento")
                        .WithMany("VagasDoEstacionamento")
                        .HasForeignKey("EstacionamentoHandle");
                });
#pragma warning restore 612, 618
        }
    }
}
